import dayjs from 'dayjs'
import { CalendarRange, ChevronLeft, ChevronRight, Factory } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { LINES, type ProductionRecord } from '../types'

type Scale='day'|'week'|'month'
const hours={day:24,week:168,month:720}

export function GanttPage(){
  const [records,setRecords]=useState<ProductionRecord[]>([]);const [line,setLine]=useState('');const [scale,setScale]=useState<Scale>('day');const [anchor,setAnchor]=useState(dayjs().startOf('day'));const [loading,setLoading]=useState(true)
  useEffect(()=>{setLoading(true);api.gantt(line).then(setRecords).finally(()=>setLoading(false))},[line])
  const span=hours[scale]; const start=scale==='day'?anchor.startOf('day'):scale==='week'?anchor.startOf('week'):anchor.startOf('month');const end=start.add(span,'hour')
  const visible=useMemo(()=>records.filter(r=>[r.plannedStartTime,r.plannedEndTime,r.actualStartTime,r.actualEndTime].some(v=>v&&dayjs(v).isBefore(end)&&dayjs(v).isAfter(start.subtract(1,'day')))),[records,start.valueOf(),end.valueOf()])
  const rows=LINES.filter(row=>(!line||row===line)&&visible.some(record=>record.productionLine===row)); const position=(date:string)=>Math.max(0,Math.min(100,dayjs(date).diff(start,'minute')/(span*60)*100));
  const Bar=({r,type}:{r:ProductionRecord;type:'planned'|'actual'})=>{const s=type==='planned'?r.plannedStartTime:r.actualStartTime;const e=type==='planned'?r.plannedEndTime:r.actualEndTime;if(!s||!e)return null;const left=position(s),right=position(e);if(right<=0||left>=100)return null;const over=type==='actual'&&r.plannedEndTime&&dayjs(e).isAfter(r.plannedEndTime);return <Link to={`/admin/records/${r.id}/edit`} title={`${r.productName}\n${r.quantityMaru}丸 / ${r.quantityBox}箱\n${r.specSummary||''}`} className={`absolute flex h-7 min-w-8 items-center overflow-hidden rounded px-2 text-[11px] font-bold shadow-sm transition hover:z-20 hover:brightness-95 ${type==='planned'?'bg-amber-300 text-amber-950':over?'bg-red-700 text-white':'bg-red-400 text-white'}`} style={{left:`${left}%`,width:`${Math.max(1,right-left)}%`,top:type==='planned'?7:38}}><span className="truncate">{type==='planned'?'預計':'實際'}｜{r.productName} · {r.quantityMaru}丸/{r.quantityBox}箱</span></Link>}
  const ticks=scale==='day'?Array.from({length:24},(_,i)=>i):scale==='week'?Array.from({length:8},(_,i)=>i*24):Array.from({length:11},(_,i)=>i*72)
  const move=(n:number)=>setAnchor(anchor.add(n,scale))
  return <div className="mx-auto max-w-[1600px] px-4 py-6 lg:px-8 lg:py-8"><div className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="mb-1 text-sm font-bold uppercase tracking-widest text-blue-700">Production Schedule</p><h1 className="text-2xl font-black text-slate-900 sm:text-3xl">產線排程甘特圖</h1><p className="mt-1 text-sm text-slate-500">產線為縱軸、時間為橫軸；點擊時間條可編輯紀錄。</p></div><div className="flex flex-wrap items-center gap-2"><select className="input w-auto" value={line} onChange={e=>setLine(e.target.value)}><option value="">所有產線</option>{LINES.map(x=><option key={x}>{x}</option>)}</select><div className="flex rounded-lg border bg-white p-1">{(['day','week','month']as Scale[]).map((x,i)=><button key={x} onClick={()=>setScale(x)} className={`rounded-md px-3 py-1.5 text-sm font-bold ${scale===x?'bg-blue-700 text-white':'text-slate-600'}`}>{['日','週','月'][i]}</button>)}</div></div></div>
    <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div className="flex items-center gap-2"><button className="rounded-lg border p-2" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button className="btn-secondary" onClick={()=>setAnchor(dayjs().startOf('day'))}>今天</button><button className="rounded-lg border p-2" onClick={()=>move(1)}><ChevronRight size={18}/></button><b className="ml-2 text-sm sm:text-base">{start.format('YYYY/MM/DD')} — {end.format('YYYY/MM/DD')}</b></div><div className="flex gap-4 text-xs font-bold"><span className="flex items-center gap-2"><i className="size-3 rounded bg-amber-300"/>預計時間</span><span className="flex items-center gap-2"><i className="size-3 rounded bg-red-400"/>實際時間</span><span className="flex items-center gap-2"><i className="size-3 rounded bg-red-700"/>超時</span></div></div>
      <div className="overflow-x-auto"><div className="min-w-[900px]"><div className="grid grid-cols-[110px_1fr] border-b bg-slate-50"><div className="border-r p-3 text-xs font-bold text-slate-500">產線</div><div className="relative h-12">{ticks.map(h=><span key={h} className="absolute top-3 -translate-x-1/2 text-[11px] font-semibold text-slate-500" style={{left:`${h/span*100}%`}}>{start.add(h,'hour').format(scale==='day'?'HH:mm':'MM/DD')}</span>)}</div></div>{loading?<div className="p-16 text-center text-slate-500">排程載入中…</div>:rows.map(row=><div key={row} className="grid grid-cols-[110px_1fr] border-b last:border-0"><div className="flex min-h-20 items-center gap-2 border-r bg-slate-50 px-4 font-black"><Factory size={16} className="text-blue-700"/>{row}</div><div className="relative min-h-20 bg-[linear-gradient(to_right,#e2e8f0_1px,transparent_1px)] bg-[length:calc(100%/7)_100%]">{ticks.map(h=><i key={h} className="absolute inset-y-0 border-l border-slate-200" style={{left:`${h/span*100}%`}}/>)}{visible.filter(r=>r.productionLine===row).flatMap(r=>[<Bar key={`${r.id}p`} r={r} type="planned"/>,<Bar key={`${r.id}a`} r={r} type="actual"/>])}</div></div>)}</div></div>
      {!loading&&visible.length===0&&<div className="border-t p-8 text-center text-slate-500"><CalendarRange className="mx-auto mb-2 text-slate-300"/><p>此時間區間沒有完整的排程資料</p></div>}
    </section></div>
}
